Traceback (most recent call last):
  File "/home/timscripts/keepa_api/keepa-deals/Keepa_Deals.py", line 65, in <module>
    main()
  File "/home/timscripts/keepa_api/keepa-deals/Keepa_Deals.py", line 30, in main
    api_key = config['keepa_api_key']
              ~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'keepa_api_key'
